/**
 * Sahayak AI — Service Details & Task Guidance Experience
 * 
 * Source of Truth: docs/source-of-truth/UI.md Section 20 & DATA-CONTRACTS.md Section 8, 30
 * Phase: P05 — Services & Deterministic Task Guidance
 * 
 * Aggregates verified service metadata, document checklist, deterministic task wizard,
 * and official government outbound portal links.
 * 
 * Invariants:
 * 1. URLs are strictly from verified data; never generated by AI.
 * 2. External links require target="_blank" rel="noopener noreferrer".
 * 3. Does not post, autofill, or submit applications to government portals.
 */

import React from "react";
import type { Service } from "../../core/shared/types";
import { useLanguage } from "../../core/language";
import { DocumentChecklist } from "./DocumentChecklist";
import { TaskJourney } from "./TaskJourney";
import { Button, Badge, Alert } from "../ui";
import { Link } from "../../router";

export interface ServiceDetailsProps {
  service: Service;
  onBack?: () => void;
}

export const ServiceDetails: React.FC<ServiceDetailsProps> = ({ service, onBack }) => {
  const { language, t } = useLanguage();

  const serviceName = service.name[language] || service.name.en;
  const serviceDesc = service.description[language] || service.description.en;

  const officialSource = service.officialSource;
  const hasOfficialUrl = Boolean(officialSource && officialSource.url);

  return (
    <div className="service-details-view" style={{ maxWidth: "1000px", margin: "0 auto" }}>
      {/* Back Navigation Bar */}
      <div style={{ marginBottom: "var(--space-6)" }}>
        <Link
          href="/services"
          onClick={onBack}
          style={{ textDecoration: "none" }}
          aria-label={t("backToServices")}
        >
          <Button variant="secondary" size="sm">
            ← {t("backToServices")}
          </Button>
        </Link>
      </div>

      {/* Service Header Header Card */}
      <div
        style={{
          backgroundColor: "var(--surface)",
          border: "1px solid var(--border)",
          borderRadius: "var(--radius-card)",
          padding: "var(--space-6)",
          boxShadow: "var(--shadow-card)",
          marginBottom: "var(--space-6)",
        }}
      >
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: "var(--space-2)",
            marginBottom: "var(--space-2)",
            flexWrap: "wrap",
          }}
        >
          <Badge variant="info">{service.category}</Badge>
          <Badge variant="neutral">{service.state}</Badge>
          <span style={{ fontSize: "0.8125rem", color: "var(--text-muted)", marginLeft: "auto" }}>
            ID: <code>{service.id}</code>
          </span>
        </div>

        <h1
          style={{
            fontSize: "2rem",
            color: "var(--sahayak-blue-dark)",
            margin: "var(--space-2) 0 var(--space-4) 0",
            lineHeight: "1.2",
          }}
        >
          {serviceName}
        </h1>

        <div style={{ marginBottom: "var(--space-4)" }}>
          <h2
            style={{
              fontSize: "1rem",
              fontWeight: 600,
              color: "var(--text-primary)",
              marginBottom: "var(--space-1)",
            }}
          >
            {t("whatIsIt")}
          </h2>
          <p
            style={{
              fontSize: "1rem",
              color: "var(--text-secondary)",
              lineHeight: "1.6",
              margin: 0,
            }}
          >
            {serviceDesc}
          </p>
        </div>

        {/* Quick Jump Anchor to Task Guidance */}
        <div style={{ display: "flex", gap: "var(--space-3)", flexWrap: "wrap" }}>
          <a href="#task-journey" style={{ textDecoration: "none" }}>
            <Button variant="primary">
              🧭 {t("stepRoadmap")} ({service.steps.length} {t("stepsCount")})
            </Button>
          </a>
          {hasOfficialUrl && (
            <a
              href={officialSource.url}
              target="_blank"
              rel="noopener noreferrer"
              style={{ textDecoration: "none" }}
            >
              <Button variant="outline">
                🏛️ {t("applyOnPortal")} ↗
              </Button>
            </a>
          )}
        </div>
      </div>

      {/* Mandatory Document Checklist Section */}
      <section style={{ marginBottom: "var(--space-8)" }} aria-label={t("requiredDocuments")}>
        <DocumentChecklist
          serviceId={service.id}
          documents={service.documents}
        />
      </section>

      {/* Deterministic Task Journey Section */}
      <section
        id="task-journey"
        style={{ marginBottom: "var(--space-8)", scrollMarginTop: "80px" }}
        aria-label={t("stepRoadmap")}
      >
        <TaskJourney service={service} />
      </section>

      {/* Official Government Source Card */}
      <section style={{ marginBottom: "var(--space-8)" }} aria-label={t("officialSource")}>
        <div
          className="official-source-card"
          style={{
            backgroundColor: "var(--surface)",
            border: "1px solid var(--border)",
            borderLeft: "4px solid var(--sahayak-blue)",
            borderRadius: "var(--radius-card)",
            padding: "var(--space-6)",
            boxShadow: "var(--shadow-card)",
          }}
        >
          <div
            style={{
              display: "flex",
              justifyContent: "space-between",
              alignItems: "flex-start",
              flexWrap: "wrap",
              gap: "var(--space-3)",
            }}
          >
            <div>
              <span
                style={{
                  fontSize: "0.75rem",
                  fontWeight: 700,
                  color: "var(--sahayak-blue-dark)",
                  textTransform: "uppercase",
                  letterSpacing: "0.05em",
                  display: "block",
                  marginBottom: "var(--space-1)",
                }}
              >
                🏛️ {t("officialSource")}
              </span>
              <h3
                style={{
                  margin: "0 0 var(--space-2) 0",
                  fontSize: "1.25rem",
                  color: "var(--text-primary)",
                }}
              >
                {officialSource?.name || "Government of Maharashtra"}
              </h3>
              <p
                style={{
                  margin: 0,
                  fontSize: "0.875rem",
                  color: "var(--text-secondary)",
                }}
              >
                {t("officialSourceVerified")}
                {officialSource?.lastVerified && (
                  <span> • Last verified: {officialSource.lastVerified}</span>
                )}
              </p>
            </div>

            <div>
              {hasOfficialUrl ? (
                <a
                  href={officialSource.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  style={{ textDecoration: "none" }}
                  aria-label={`${t("applyOnPortal")}: ${officialSource.name}`}
                >
                  <Button variant="primary">
                    {t("applyOnPortal")} ↗
                  </Button>
                </a>
              ) : (
                <Alert variant="warning" style={{ margin: 0, fontSize: "0.875rem" }}>
                  {t("unverifiedApplicationRoute")}
                </Alert>
              )}
            </div>
          </div>
        </div>
      </section>

      {/* Mandatory Civic Safety & Procedural Disclaimer */}
      <Alert variant="info" style={{ marginBottom: "var(--space-8)" }}>
        <strong>⚠️ {t("disclaimer")}</strong>
      </Alert>
    </div>
  );
};
