/**
 * Sahayak AI — Official Government Authority & Source Box
 * 
 * Source of Truth: docs/source-of-truth/UI.md Section 22 & OFFICIAL-SOURCES.md Section 11-13
 * Phase: P06 — Scheme Finder
 * 
 * Renders verified government authority attribution and outbound portal action.
 * Invariants:
 * 1. URLs are strictly from verified data; never generated by AI.
 * 2. External links require target="_blank" rel="noopener noreferrer".
 * 3. Clearly distinguishes between verified application link and information-only link.
 */

import React from "react";
import type { OfficialSource } from "../../core/shared/types";
import { useLanguage } from "../../core/language";
import { Button, Alert } from "../ui";

export interface OfficialSourceBoxProps {
  officialSource: OfficialSource;
  lastVerified?: string;
}

export const OfficialSourceBox: React.FC<OfficialSourceBoxProps> = ({
  officialSource,
  lastVerified,
}) => {
  const { t } = useLanguage();

  const hasUrl = Boolean(officialSource && officialSource.url && officialSource.url.startsWith("https://"));
  const verifiedDate = lastVerified || officialSource.lastVerified || "2026-09-25";

  return (
    <div
      className="official-source-box"
      style={{
        backgroundColor: "var(--surface)",
        border: "1px solid var(--border)",
        borderLeft: "4px solid var(--sahayak-blue)",
        borderRadius: "var(--radius-card)",
        padding: "var(--space-6)",
        boxShadow: "var(--shadow-card)",
      }}
    >
      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "flex-start",
          flexWrap: "wrap",
          gap: "var(--space-3)",
        }}
      >
        <div>
          <span
            style={{
              fontSize: "0.75rem",
              fontWeight: 700,
              color: "var(--sahayak-blue-dark)",
              textTransform: "uppercase",
              letterSpacing: "0.05em",
              display: "block",
              marginBottom: "var(--space-1)",
            }}
          >
            🏛️ {t("officialAuthority")}
          </span>
          <h3
            style={{
              margin: "0 0 var(--space-2) 0",
              fontSize: "1.125rem",
              color: "var(--text-primary)",
              lineHeight: "1.4",
            }}
          >
            {officialSource.name}
          </h3>
          <p
            style={{
              margin: 0,
              fontSize: "0.8125rem",
              color: "var(--text-muted)",
            }}
          >
            Verified Government Authority • Last verified: <strong>{verifiedDate}</strong>
          </p>
        </div>

        <div>
          {hasUrl ? (
            <a
              href={officialSource.url}
              target="_blank"
              rel="noopener noreferrer"
              style={{ textDecoration: "none" }}
              aria-label={`${t("applyOnOfficialPortal")}: ${officialSource.name}`}
            >
              <Button variant="primary">
                {t("applyOnOfficialPortal")} ↗
              </Button>
            </a>
          ) : (
            <Alert variant="warning" style={{ margin: 0, fontSize: "0.875rem" }}>
              {t("officialRouteNotVerified")}
            </Alert>
          )}
        </div>
      </div>
    </div>
  );
};
